;;
(require 'color-theme)

(defun color-theme-oceandeep ()
  "Color Theme, created 2004-12-25 by crazycool."
  (interactive)
  (color-theme-install
   '(color-theme-oceandeep nil nil
     (widget-single-line-field-face ((t (:inherit widget-field-face))))
     (widget-inactive-face ((t (:foreground "light gray"))))
     (widget-field-face ((t (:background "#2A3B5E" :foreground "white"))))
     (widget-documentation-face ((t (:foreground "lime green"))))
     (widget-button-pressed-face ((t (:foreground "tomato"))))
     (widget-button-face ((t (:bold t :weight bold))))
     (wb-line-number-scroll-bar-face ((t (:background "LightSkyBlue3"))))
     (wb-line-number-face ((t (:background "#0B162E" :foreground "LightSky Blue3"))))
     (underline ((t (:underline t))))
     (trailing-whitespace ((t (:background "salmon"))))
     (tooltip ((((class color)) (:background "lightyellow" :foreground "black" :height 120 :family "Helvetica"))))
     (tex-verbatim ((t (:inherit font-lock-doc-face))))
     (tabbar-default-face ((t (:inherit variable-pitch :background "#5E67E6" :foreground "black"))))
     (tabbar-button-face ((t (:inherit tabbar-default-face :background "#999999" :foreground "blue" :box (:line-width 2 :color "white" :style released-button)))))
     (tabbar-selected-face ((t (:inherit tabbar-default-face :background "#FFE957" :foreground "black" :box (:line-width 1 :color "#F0D800" :style pressed-button)))))
     (tabbar-unselected-face ((t (:inherit tabbar-default-face :background "#D8FF57" :foreground "black" :box (:line-width 1 :color "#A9D400" :style released-button)))))
     (speedbar-button-face ((t (:foreground "yellowgreen"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "#87f5e6"))))
     (speedbar-highlight-face ((t (:foreground "#FBFB7e" :underline t))))
     (speedbar-selected-face ((t (:foreground "pink"))))
     (speedbar-tag-face ((t (:foreground "gold2"))))
     (show-paren-mismatch-face ((t (:background "pink2" :foreground "blue4"))))
     (show-paren-match-face ((t (:background "#70A6D6" :foreground "blue4"))))
     (sgml-namespace-face ((t (:foreground "#96CEF8"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (region ((t (:background "#F0E171" :foreground "#103040"))))
     (quack-pltish-class-defn-face ((((class color) (background dark)) (:inherit font-lock-constant-face :weight bold))))
     (quack-pltish-comment-face ((((class color) (background dark)) (:inherit font-lock-comment-face))))
     (quack-pltish-defn-face ((t (:inherit font-lock-function-name-face :weight bold))))
     (quack-pltish-module-defn-face ((((class color) (background dark)) (:inherit font-lock-constant-face :weight bold))))
     (quack-pltish-paren-face ((((class color) (background dark)) (:inherit default))))
     (quack-pltish-selfeval-face ((((class color) (background dark)) (:inherit font-lock-variable-name-face))))
     (quack-threesemi-semi-face ((((class color) (background dark)) (:inherit font-lock-doc-face :background "darkslategrey"))))
     (quack-threesemi-text-face ((((class color) (background dark)) (:background "darkslategrey" :foreground "wheat"))))
     (mouse ((t (:background "PaleTurquoise2"))))
     (mode-line ((t (:background "#354566" :foreground "#C1CCE3" :box (:line-width 1 :color "#64798F" :style released-button)))))
     (mode-line-inactive ((t (:background "#424A5C" :foreground "#B2C5D1" :box (:line-width 1 :color "#424A5C")))))
     (minibuffer-prompt ((t (:foreground "#FBFB7E"))))
     (match ((t (:background "DarkOliveGreen4" :foreground "white"))))
     (isearch ((t (:background "#F0897F" :foreground "black"))))
     (isearch-lazy-highlight-face ((t (:background "#9FC98D" :foreground "black"))))
     (ido-subdir-face ((t (:foreground "#EEE48E"))))
     (ido-subdir ((t (:foreground "#EEE48E"))))
     (ido-only-match-face ((t (:foreground "#BEF284"))))
     (ido-only-match ((t (:foreground "#BEF284"))))
     (ido-indicator-face ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-first-match-face ((t (:bold t :foreground "#A3F8AF" :weight bold))))
     (ido-first-match ((t (:bold t :foreground "#A3F8AF" :weight bold))))
     (info-xref-visited ((t (:inherit info-xref :foreground "lightblue2"))))
     (info-title-4 ((t (:inherit (variable-pitch font-lock-variable-name-face) :weight bold :height 1.1))))
     (info-title-4-face ((t (:inherit (variable-pitch font-lock-variable-name-face) :weight bold :height 1.1))))
     (info-menu-header ((t (:inherit variable-pitch :weight bold :height 1.3))))
     (holiday-face ((t (:background "chocolate4"))))
     (highlight ((t (:background "#FFD0C9" :foreground "black"))))
     (header-line ((t (:width normal :weight normal :slant normal :box (:line-width 1 :color "#507D94") :background "grey20" :foreground "grey90" :box nil))))
     (fringe ((t (:background "#060C1A"))))
     (font-lock-warning-face ((t (:foreground "Pink"))))
     (font-lock-variable-name-face ((t (:foreground "#B5CF76"))))
     (font-lock-type-face ((t (:foreground "#9BEEB8"))))
     (font-lock-string-face ((t (:foreground "#F0A4A4"))))
     (font-lock-preprocessor-face ((t (:foreground "#96CEF8"))))
     (font-lock-keyword-face ((t (:foreground "#78F5E6"))))
     (font-lock-function-name-face ((t (:foreground "#96CEF8"))))
     (font-lock-doc-face ((t (:foreground "#FFA87A"))))
     (font-lock-constant-face ((t (:foreground "#D8ACDD"))))
     (font-lock-comment-face ((t (:foreground "#DEBC83"))))
     (font-lock-builtin-face ((t (:foreground "#96CEF8"))))
     (emacs-wiki-link-face ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
     (emacs-wiki-header-6 ((t (:bold t :weight bold :height 0.9))))
     (emacs-wiki-header-5 ((t (:bold t :weight bold :height 1.0))))
     (emacs-wiki-header-4 ((t (:bold t :foreground "yellowgreen" :slant normal :weight bold :height 120 :width normal))))
     (emacs-wiki-header-3 ((t (:bold t :foreground "skyblue" :slant normal :weight bold :height 136 :width normal))))
     (emacs-wiki-header-2 ((t (:bold t :foreground "lightpink1" :underline t :slant normal :weight bold :height 151 :width normal))))
     (emacs-wiki-header-1 ((t (:bold t :weight bold :height 1.4))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
     (diary-face ((t (:foreground "yellow"))))
     (custom-variable-tag-face ((t (:bold t :family "helv" :foreground "light blue" :weight bold :height 1.2))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-saved-face ((t (:underline t))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-group-tag-face-1 ((t (:bold t :family "helv" :foreground "pink" :weight bold :height 1.2))))
     (custom-group-tag-face ((t (:bold t :foreground "light blue" :weight bold :height 1.2))))
     (custom-face-tag-face ((t (:bold t :family "helv" :weight bold :height 1.2))))
     (custom-documentation-face ((t (nil))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (cursor ((((class color) (back dark)) (:background "PaleTurquoise2"))
              (((class color) (background light)) (:background "red"))))
     (completions-first-difference ((t (:bold t :width normal :weight bold :foreground "gold2"))))
     (compilation-warning-face ((t (:bold t :foreground "#e9b121" :weight bold))))
     (compilation-info-face ((t (:bold t :foreground "#8eea77" :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (cvs-filename-face ((((class color) (background dark)) (:inherit font-lock-function-name-face))))
     (cvs-handled-face ((((class color) (background dark)) (:inherit font-lock-variable-name-face))))
     (cvs-header-face ((t (:inherit font-lock-constant-face))))
     (cvs-marked-face ((t (:foreground "lightgreen"))))
     (cvs-msg-face ((t (:weight bold))))
     (cvs-need-action-face ((((class color) (background dark)) (:inherit font-lock-comment-face :foreground "gold2"))))
     (cvs-unknown-face ((((class color) (background dark)) (:inherit font-lock-string-face))))
     (cvs-filename ((((class color) (background dark)) (:inherit font-lock-function-name-face))))
     (cvs-handled ((((class color) (background dark)) (:inherit font-lock-variable-name-face))))
     (cvs-header ((t (:inherit font-lock-constant-face))))
     (cvs-marked ((t (:foreground "lightgreen"))))
     (cvs-msg ((t (:weight bold))))
     (cvs-need-action ((((class color) (background dark)) (:inherit font-lock-comment-face :foreground "gold2"))))
     (cvs-unknown-face ((((class color) (background dark)) (:inherit font-lock-string-face))))
     (bm-face ((((class color) (background dark)) (:background "#C7C7E2" :foreground "Black"))))
     (bm-persistent-face ((((class color) (background dark)) (:background "#D6E2C7" :foreground "Black"))))
     (ediff-current-diff-face-A ((t (:background "#BBFFC4" :foreground "black"))))
     (ediff-current-diff-face-B ((t (:background "#FFFFBB" :foreground "black"))))
     (ediff-current-diff-face-C ((t (:background "#FFBBBB" :foreground "black"))))
     (ediff-current-diff-face-Ancestor ((t (:background "#FF7575" :foreground "black"))))
     (ediff-even-diff-face-A ((t (:background "#B6BFB7" :foreground "grey15"))))
     (ediff-even-diff-face-B ((t (:background "#BFBFB6" :foreground "grey15"))))
     (ediff-even-diff-face-C ((t (:background "#BFBFB6" :foreground "grey15"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey40" :foreground "White"))))
     (ediff-fine-diff-face-A ((t (:background "#FFB2B2" :foreground "black"))))
     (ediff-fine-diff-face-B ((t (:inherit ediff-fine-diff-face-A))))
     (ediff-fine-diff-face-C ((((class color)) (:background "Turquoise" :foreground "Black"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "pale Green" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "#B6BFB7" :foreground "black"))))
     (ediff-odd-diff-face-B ((t (:background "#BFBFB6" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "#BFBFB6" :foreground "black"))))
     (ediff-odd-diff-face-Ancestor ((((class color)) (:background "light grey" :foreground "Black"))))
     (eshell-ls-archive-face ((t (:foreground "violet"))))
     (eshell-ls-clutter-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-directory-face ((t (:foreground "SkyBlue"))))
     (eshell-ls-executable-face ((t (:foreground "light green"))))
     (eshell-ls-missing-face ((t (:foreground "salmon"))))
     (eshell-ls-symlink-face ((t (:foreground "Cyan"))))
     (eshell-prompt-face ((t (:foreground "Pink"))))
     (diff-added-face ((t (:foreground "#CAFFAB"))))
     (diff-changed-face ((t (:foreground "#FFABAB"))))
     (diff-context-face ((((class color) (background dark)) nil)))
     (diff-file-header-face ((t (:inherit diff-header-face :foreground "blue"))))
     (diff-function-face ((t (:inherit diff-context-face :underline t))))
     (diff-header-face ((((class color) (background dark)) (:background "#EDE351" :foreground "black"))))
     (diff-removed-face ((t (:foreground "#8A9496" :strike-through t))))
     (breakpoint-enabled-bitmap-face ((t (:foreground "tomato"))))
     (breakpoint-disabled-bitmap-face ((t (:foreground "grey75"))))
     (cperl-array-face ((((class color) (background dark)) (:foreground "#F9FF54"))))
     (cperl-hash-face ((((class color) (background dark)) (:foreground "#E09BC2"))))
     (cperl-nonoverridable-face ((((class color) (background dark)) (:foreground "#96CEF8"))))
     (calendar-today-face ((t (:underline t))))
     (button ((t (:underline t))))
     (border ((t (:background "black"))))
     (bm-persistent-face ((t (:background "#C7C7E2" :foreground "Black"))))
     (bm-face ((t (:background "#D6E2C7" :foreground "Black"))))
     (menu ((((type x-toolkit)) (:background "#F4F4F4" :foreground "black" :height 120 :family "Helvetica"))))
     (tool-bar ((t (:box (:line-width 1 :style released-button) :background "#F4F4F4" :foreground "black"))))
     (Buffer-menu-buffer-face ((t (:bold t :weight bold))))
     (default ((t (:background "#0B162E" :foreground "#CED9E0")))))))

(provide 'color-theme-oceandeep)
